# Prosty frontend w Node.js
FROM node:18-alpine

WORKDIR /app
COPY . .

# Instalacja zależności (np. React, ale możesz dostosować)
RUN npm install

# Komenda startowa (np. dev lub build & serve)
CMD ["npm", "start"]