
services:
  frontend:
    build:
      context: ./frontend
    ports:
      - "3000:3000"
    restart: always
    networks:
      - app-network

  backend:
    build:
      context: ./backend
    ports:
      - "4000:4000"
    restart: always
    networks:
      - app-network
    environment:
      - MONGO_URL=mongodb://mongo:27017/mydb

  mongo:
    image: mongo:latest
    restart: always
    volumes:
      - mongo_data:/data/db
    networks:
      - app-network

volumes:
  mongo_data:

networks:
  app-network:
